### PR TITLE
fix #14 and #15

### LINKED ISSUE #14: Method past_trades requires limit_trades as mandatory parameter
Bitfinex API documentation indicates `limit_trades` is optional, however the method `past_trades` requires it as mandatory parameter

### PR DESCRIPTION
**Pull request by dutu**

### CODE REVIEW

**Comment by dutu** [comment]
any chance to have this merged and new module rev released?
My travis is currently failing https://travis-ci.org/dutu/cryptox/ due to the dependencies.

The changes introduced have passed all tests, but feel free to test more if needed.
If you can't review and merge soon, pls let me know and I'll remove the dependency on this module for now. Thanks

**Comment by gferrin** [comment]
Yeah, I appreciate your pull request and will get it merged today.

**Comment by gferrin** [comment]
I like you changes, but I don't like having a `past_trades` and a `mytrades` function doing exactly the same thing but I like you new implementation for `mytrades` so I'm going to take the code for that and continue calling is `past_trades`

**Comment by dutu** [comment]
i did it as separate function to keep backward compatibility of the module, else, whoever is using  `past_trades` today can still continue using it

**Comment by dutu** [comment]
btw, Bitfinex calls the method `mytrades` :)

if you introduce API changes which are not backwards compatible, pls it would be good incrementing the major number of the module revision (1.x.x)

**Comment by gferrin** [comment]
I thought about that, but decided to do it anyways since you upped the API by a sub-version

**Comment by dutu** [comment]
yes, i did it for MINOR which is for API changes that are backwards compatible. for non-backward compatible changes is recommended that you increase the MAJOR. Reference: http://semver.org/

**Comment by gferrin** [comment]
Yeah your right - I reverted to your pull request and published it exactly as version 0.4.1 I then went back to mine and published it as 1.0.0 - Thanks for your contributions!

**Pull request merged**
